---
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: traefik
  externalIPs:
  - "192.168.99.100"
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
spec:
  ports:
  - port: 9000
    name: status
    targetPort: 8080
  selector:
    app: traefik
  externalIPs:
  - "192.168.99.100"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traefik
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
      - image: traefik:v1.4
        name: traefik
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - containerPort: 80
        - containerPort: 8080
        args:
        - --web
        - --kubernetes
        - --loglevel=ERROR